name: Echo User Input
run-name: Testing Github Actions
on: [issue_comment]
jobs: 
    issue_commented:
        name: Issue comment
        runs-on: ubuntu-latest
        steps:
            - name: commenting on the issue
              id: comment
              uses: actions/github-script@v4
              with:
                script:  |
                  const commentBody = context.payload.comment.body;
                  if (commentBody.startsWith('TriagerX')) {
                    const secondPart = commentBody.split(' ')[1];
                    if (secondPart.startsWith('http')) {
                      const issueUrl = secondPart;
                      const issueNumber = issueUrl.split('/').pop();
                      const issueRepo = issueUrl.split('/')[4];
                      const issueOwner = issueUrl.split('/')[3];
                      
                      const issue = await github.issues.get({
                        owner: issueOwner,
                        repo: issueRepo,
                        issue_number: issueNumber,
                      });

                      const issueTitle = issue.data.title;
                      const issueDescription = issue.data.body;

                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Issue Title: ${issueTitle}\nIssue Description: ${issueDescription}`,
                      });
                    } else {
                      const name = commentBody.split(' ').slice(1).join(' ');
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Hi ${name}! How can we help you today?`,
                      });
                    }
                  }
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
